#pragma once 
#include <stdbool.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <time.h>
#include <tlhelp32.h>
#include <stdint.h>
#include <initguid.h>
#include <fwpmu.h>
#include <fwpmtypes.h>
#include <ctype.h>
#include <math.h>
#include <wbemidl.h>
#include <oleauto.h>
#include <imagehlp.h>
#include <pla.h>
#include <proofofpossessioncookieinfo.h>
#include <combaseapi.h>
#include <stdio.h>
#include <ntsecapi.h>
#include <evntprov.h>
#include <wincrypt.h>

#include "badger_exports.h"
#include "lmjoin_exports.h"
#include "msvcrt_exports.h"
#include "advapi32_exports.h"
#include "kernel32_exports.h"
#include "dbgprint.h"
#include "winstructs.h"
#include "ntdll_exports.h"
#include "psapi_exports.h"
#include "shlwapi_exports.h"
#include "version_exports.h"
#include "imagehlp_exports.h"
#include "crypt32_exports.h"
